## 配置数据库连接
spring:
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ubuntumall_pms?useSSL=false&serverTimezone=UTC
## 配置mybatisplus的连接
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      # 配置id自增
      id-type: auto
server:
  port: 10000
      